"""
Markdown chunker (docling output) built to feed GLiNER without
exceeding its token limit.

Strategy:
1. Parse the markdown into semantic blocks (headers, paragraphs, tables,
   lists) with a lightweight line-based parser (no heavy dependencies
   like markdown-it-py needed for docling's clean, predictable output).
2. Measure tokens with the REAL tokenizer of your GLiNER backbone
   (usually BERT/DeBERTa-based), not a character-count heuristic.
3. Group consecutive blocks until the token budget is filled, without
   splitting a block in the middle unless the block itself is bigger
   than the limit (in which case it's split by sentences).
4. Add overlap (in tokens) between consecutive chunks so entities that
   fall right on the boundary aren't lost.
5. Tables are treated as separate atomic blocks: if they fit, they go
   with their surrounding context; if not, they'd need row-level
   splitting while keeping the header in each piece (GLiNER performs
   poorly on large tables anyway, so it's usually better to extract
   them with docling's `table.export_to_dataframe()` and process them
   with a separate tabular pipeline instead of free-text NER).

Typical usage:

    from markdown_chunker_gliner import MarkdownChunker

    chunker = MarkdownChunker(
        tokenizer_name="urchade/gliner_multi-v2.1",  # or your real backbone
        max_tokens=380,      # leave margin under the model's hard limit
        overlap_tokens=40,
    )

    chunks = chunker.chunk(markdown_text)

    for c in chunks:
        entities = gliner_model.predict_entities(c.text, labels=[...])
        # c.start_char / c.end_char let you remap entity positions back
        # to the original document if you need that for the knowledge graph
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import List, Optional

try:
    from transformers import AutoTokenizer
    _HAS_TRANSFORMERS = True
except ImportError:
    _HAS_TRANSFORMERS = False


# --------------------------------------------------------------------------
# Data structures
# --------------------------------------------------------------------------

@dataclass
class Block:
    """Minimal semantic unit extracted from the markdown."""
    text: str
    kind: str  # "header" | "paragraph" | "table" | "list"
    level: int = 0  # header level, if applicable


@dataclass
class Chunk:
    text: str
    n_tokens: int
    start_char: int
    end_char: int
    block_kinds: List[str] = field(default_factory=list)


# --------------------------------------------------------------------------
# Markdown -> semantic blocks parsing
# --------------------------------------------------------------------------

_HEADER_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_TABLE_ROW_RE = re.compile(r"^\|.*\|$")


def parse_markdown_blocks(markdown_text: str) -> List[Block]:
    """
    Lightweight line-based parser. Not a full CommonMark parser: for
    the target use case (markdown generated by docling, which is clean
    and predictable) this is enough and avoids pulling in a heavy
    dependency like markdown-it-py if you don't need it.
    """
    lines = markdown_text.split("\n")
    blocks: List[Block] = []

    buffer: List[str] = []
    in_table = False

    def flush_paragraph():
        nonlocal buffer
        if buffer:
            text = "\n".join(buffer).strip()
            if text:
                blocks.append(Block(text=text, kind="paragraph"))
            buffer = []

    for line in lines:
        stripped = line.strip()

        header_match = _HEADER_RE.match(stripped)
        if header_match:
            flush_paragraph()
            level = len(header_match.group(1))
            blocks.append(Block(text=stripped, kind="header", level=level))
            continue

        if _TABLE_ROW_RE.match(stripped):
            if not in_table:
                flush_paragraph()
                in_table = True
            buffer.append(line)
            continue
        else:
            if in_table:
                text = "\n".join(buffer).strip()
                blocks.append(Block(text=text, kind="table"))
                buffer = []
                in_table = False

        if stripped == "":
            flush_paragraph()
            continue

        buffer.append(line)

    if in_table:
        blocks.append(Block(text="\n".join(buffer).strip(), kind="table"))
    else:
        flush_paragraph()

    return blocks


# --------------------------------------------------------------------------
# Main chunker
# --------------------------------------------------------------------------

class MarkdownChunker:
    def __init__(
        self,
        tokenizer_name: str = "microsoft/deberta-v3-base",
        max_tokens: int = 380,
        overlap_tokens: int = 40,
        keep_last_header_as_context: bool = True,
    ):
        """
        tokenizer_name: use the real backbone of your GLiNER checkpoint.
            Common examples: "microsoft/deberta-v3-base" (English
            gliner_base), "microsoft/mdeberta-v3-base" (gliner_multi).
            Check your model's config.json if you're not sure.
        max_tokens: budget per chunk. Leave margin under the model's
            actual limit (e.g. if the model supports 384, use 350-380
            to leave room for labels/prompt if your wrapper adds any).
        overlap_tokens: how many tokens from the end of a chunk are
            repeated at the start of the next one, so entities aren't
            cut right at the boundary.
        keep_last_header_as_context: if True, prepends the last seen
            header to each chunk (gives GLiNER semantic context, e.g.
            "## Exclusion clause" before the paragraph).
        """
        if not _HAS_TRANSFORMERS:
            raise ImportError(
                "You need `pip install transformers` to measure tokens "
                "with the real tokenizer. Without this, chunks can end "
                "up longer than what GLiNER actually supports."
            )
        self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
        self.max_tokens = max_tokens
        self.overlap_tokens = overlap_tokens
        self.keep_last_header_as_context = keep_last_header_as_context

    def _count_tokens(self, text: str) -> int:
        return len(self.tokenizer.encode(text, add_special_tokens=False))

    def _split_long_block(self, text: str) -> List[str]:
        """A single block exceeds max_tokens: split it by sentences."""
        sentences = re.split(r"(?<=[.!?])\s+", text)
        pieces: List[str] = []
        current = ""
        current_tokens = 0
        for sent in sentences:
            sent_tokens = self._count_tokens(sent)
            if sent_tokens > self.max_tokens:
                # a single giant sentence (rare, but can happen with
                # misdetected tables): brute-force split by tokens
                ids = self.tokenizer.encode(sent, add_special_tokens=False)
                for i in range(0, len(ids), self.max_tokens):
                    piece_ids = ids[i:i + self.max_tokens]
                    pieces.append(self.tokenizer.decode(piece_ids))
                continue
            if current_tokens + sent_tokens > self.max_tokens:
                if current:
                    pieces.append(current.strip())
                current = sent
                current_tokens = sent_tokens
            else:
                current = f"{current} {sent}".strip()
                current_tokens += sent_tokens
        if current:
            pieces.append(current.strip())
        return pieces

    def chunk(self, markdown_text: str) -> List[Chunk]:
        blocks = parse_markdown_blocks(markdown_text)

        chunks: List[Chunk] = []
        current_texts: List[str] = []
        current_kinds: List[str] = []
        current_tokens = 0
        last_header = ""

        char_cursor = 0  # approximate, for start_char/end_char

        def flush_chunk():
            nonlocal current_texts, current_kinds, current_tokens
            if not current_texts:
                return
            prefix = f"{last_header}\n" if (
                self.keep_last_header_as_context and last_header
            ) else ""
            text = prefix + "\n\n".join(current_texts)
            chunks.append(Chunk(
                text=text,
                n_tokens=self._count_tokens(text),
                start_char=char_cursor,
                end_char=char_cursor + len(text),
                block_kinds=list(current_kinds),
            ))
            current_texts = []
            current_kinds = []
            current_tokens = 0

        for block in blocks:
            if block.kind == "header":
                last_header = block.text
                continue  # the header itself isn't a content block

            block_tokens = self._count_tokens(block.text)

            if block_tokens > self.max_tokens:
                # the block doesn't fit whole in any chunk: flush what
                # we've accumulated first, then split it
                flush_chunk()
                for piece in self._split_long_block(block.text):
                    chunks.append(Chunk(
                        text=piece,
                        n_tokens=self._count_tokens(piece),
                        start_char=char_cursor,
                        end_char=char_cursor + len(piece),
                        block_kinds=[block.kind],
                    ))
                continue

            if current_tokens + block_tokens > self.max_tokens:
                flush_chunk()
                if self.overlap_tokens > 0 and chunks:
                    overlap_text = self._tail_by_tokens(
                        chunks[-1].text, self.overlap_tokens
                    )
                    if overlap_text:
                        current_texts.append(overlap_text)
                        current_kinds.append("overlap")
                        current_tokens += self._count_tokens(overlap_text)

            current_texts.append(block.text)
            current_kinds.append(block.kind)
            current_tokens += block_tokens

        flush_chunk()
        return chunks

    def _tail_by_tokens(self, text: str, n_tokens: int) -> str:
        ids = self.tokenizer.encode(text, add_special_tokens=False)
        tail_ids = ids[-n_tokens:]
        return self.tokenizer.decode(tail_ids)


# --------------------------------------------------------------------------
# End-to-end example with docling
# --------------------------------------------------------------------------

if __name__ == "__main__":
    from docling.document_converter import DocumentConverter

    converter = DocumentConverter()
    result = converter.convert("sample_policy.pdf")
    markdown_text = result.document.export_to_markdown()

    chunker = MarkdownChunker(
        tokenizer_name="microsoft/mdeberta-v3-base",  # match your checkpoint
        max_tokens=350,
        overlap_tokens=30,
    )

    chunks = chunker.chunk(markdown_text)
    print(f"Generated {len(chunks)} chunks")
    for i, c in enumerate(chunks):
        print(f"--- chunk {i} ({c.n_tokens} tokens, blocks: {c.block_kinds}) ---")
        print(c.text[:200], "...\n")

    # from gliner import GLiNER
    # model = GLiNER.from_pretrained("urchade/gliner_multi-v2.1")
    # labels = ["person", "policy", "date", "amount", "clause"]
    # all_entities = []
    # for c in chunks:
    #     ents = model.predict_entities(c.text, labels)
    #     all_entities.extend(ents)  # dedupe by overlap if needed
